"""Added history table

Revision ID: 71f7120f6c3c
Revises: ea699c4fdb96
Create Date: 2020-05-05 21:34:35.191184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f7120f6c3c'
down_revision = 'ea699c4fdb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_history'))
    )
    op.create_index(op.f('ix_history_type'), 'history', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_type'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
