"""Added unique

Revision ID: 8427846806a9
Revises: af2374120e0c
Create Date: 2020-05-22 22:53:02.379212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8427846806a9'
down_revision = 'af2374120e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_token', table_name='token')
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=True)
    op.create_unique_constraint('full_phone_constraint', 'user', ['phone', 'country'])
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_constraint('full_phone_constraint', 'user', type_='unique')
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.create_index('ix_token_token', 'token', ['token'], unique=False)
    # ### end Alembic commands ###
