databases:
  auth-db:
    host: nous-auth-db
    port: 5432
    user: nous
    password: nous123
    database: nous_auth

services:

loggers:
  version: 1
  disable_existing_loggers: False
  # форматтеры
  formatters:
    default:
      format: "%(pathname)s -[%(asctime)s] - %(levelname)s: %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
      stream: ext://sys.stdout

settings:
  api: 0

