databases:
  auth-db:
    host: nous-auth-db
    port: 5432
    user: nous
    password: nous123
    database: nous_auth

services:

loggers:
  default:
    version: 1
    disable_existing_loggers: False
    # форматтеры
    formatters:
      default:
        format: "%(asctime)s - [%(pathname)s]: %(message)s"

    handlers:
      console:
        class: logging.StreamHandler
        formatter: default
        level: DEBUG
        stream: ext://sys.stdout

    loggers:
      auth:
        level: DEBUG
        handlers: [dev_log, logstash, console]
        propagate: False

settings:
  api: 0

